// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.663
package publiccomponent

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func MenuBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"menu-bar\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = animation().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = navBar().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func animation() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"hold-animation\"><div class=\"wrapper-animation\"><div class=\"animation\" id=\"lottie-animation\"></div></div><div class=\"quote\"><p>'If You Can't Measure It, You Can't Manage It'</p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func navBar() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"nav-bar\"><!-- <div class=\"triangle\"></div> --><nav><ul><li class=\"wide\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_1.svg\" class=\"icon\">Screentime</a></li><li class=\"wide\"><a href=\"#\" class=\"links wide\" tabindex=\"0\"><img src=\"assets/svg/no_2.svg\" class=\"icon\">Focus</a></li><li class=\"wide\"><a href=\"#\" class=\"links wide\" tabindex=\"0\"><img src=\"assets/svg/no_3.svg\" class=\"icon\">Stats</a></li><li class=\"wide\"><a href=\"#\" class=\"links wide\" tabindex=\"0\"><img src=\"assets/svg/no_4.svg\" class=\"icon\">Memories</a></li><li class=\"hidden\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_5_settings.svg\" class=\"icon\">Settings</a></li><li class=\"hidden\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_6_logout.svg\" class=\"icon\">Logout</a></li><li class=\"narrow\" title=\"Screentime\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_1.svg\" class=\"icon\"></a></li><li class=\"narrow\" title=\"Focus\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_2.svg\" class=\"icon\"></a></li><li class=\"narrow\" title=\"Stats\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_3.svg\" class=\"icon\"></a></li><li class=\"narrow\" title=\"Memories\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_4.svg\" class=\"icon\"></a></li><li class=\"narrow\" title=\"Settings\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_5_settings.svg\" class=\"icon\"></a></li><li class=\"narrow\" title=\"Logout\"><a href=\"#\" class=\"links\" tabindex=\"0\"><img src=\"assets/svg/no_6_logout.svg\" class=\"icon\"></a></li></ul></nav></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
